### PR TITLE
Run Hooks on elements of projects and in modify project

### PR DESCRIPTION
**Pull request by DerBeutlin**
As mentioned in https://github.com/Trevoke/org-gtd.el/issues/114#issuecomment-1440277890 there are a few ``org-gtd--decorate-item``  missing.

Unfortunately I couldn't figure out why we need the reverse in ``org-gtd--nextify`` in therefore the elements are decorated in reversed order.

Also the tests fail (already for the master branch) when I try to run them in emacs directly. Therefore I probably need to set up eldev.

### CODE REVIEW

**Comment by DerBeutlin** [comment]
I could imagine the failures in the test originate from not setting enough tags in the ``kbd-macro`` as I said I need to get the tests to run on my side

**Comment by Trevoke** [comment]
Ah, thank you, that's great!

I can't figure out / remember why we need the reverse, but I know that last time I tried to remove it because I thought I fixed the need for it, tests broke again :p I'll have to look at this again, that `reverse` is mind-boggling, and it really feels like it shouldn't be necessary for this code.
 
This being said, we can adjust this function so that it runs through these twice, once in user-order and once however it needs to run through them for other logic - it's not like it's going to be a thousand headings, so I'm not worried about a performance hit here. 

And yes, emacs testing basically _requires_ running in a separate instance of emacs, because we can't assume anything about your current emacs instance, and who knows what horrible things you've done to it :D 

Two notes:
1. You don't need the `progn` inside the lambda - the lambda accepts an arbitrary number of sexps.
2. This is closely related to the changes I made in https://github.com/Trevoke/org-gtd.el/tree/more-flexible-organization (especially, I think, your astute creation of the `decorate-org-element` function), so let me know how my thoughts mesh with yours on that front?

**Comment by Trevoke** [comment]
This looks pretty great. I think the only two things stopping a merge for this are:

1. I think you're right and it would be nice if the decorating happened in the order the user expects it to
2. I think there should be something either added to a test or a new test checking that the project tasks are decorated (I would just check that the tag shows up on the task line in the agenda buffer)

Let me know if you would like help with either of these two things!

**Comment by DerBeutlin** [comment]
I did both.

I now do the decorating in a seperate "loop"
Here I use the matcher Level 2 to only match against the children. Because otherwise I decorated the project headline twice. Is this in general alright? Because we don't do this matching in the other org-map-entries call. So what would happen if the children had children of their own?

**Comment by Trevoke** [comment]
LEVEL=2 is precisely how project actions are defined in org-gtd, so you're fine on that front.

People can do whatever they want, but I've found it very difficult to make project tasks suitably flexible, so I defined them as a sequential list of tasks in the form of level 2 headings.

**Comment by Trevoke** [comment]
Thank you for fixing this!

**Pull request merged**
